const COLOR_COUNTER_LIMITED = 444
const COLOR_CHANGE_STEP = 6
const COLOR_MAX_RGB = 255
const COLOR_START = 70

const RELIABILITY_LIMIT = 1

export {COLOR_CHANGE_STEP, COLOR_COUNTER_LIMITED, COLOR_MAX_RGB, COLOR_START, RELIABILITY_LIMIT}